version: "3.8"
services:
  webapp:
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - mysql
#      - cups
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - ".:/var/www/html/"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: kim7795004
      #MYSQL_DATABASE: ca
      MYSQL_USER: doseok
      MYSQL_PASSWORD: kim7795004
    volumes:
      - "./mysqldata:/var/lib/mysql"

#  cups:
#    image: olbat/cupsd:latest
#    container_name: cups
#    restart: always
#    ports:
#      - "631:631"
#    expose:
#      - "631"
